### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by tjvantoll** [bsatrom/jquery-ui-forms#1]
@bsatrom Close this. Let's see if I can re-open it.

**Comment by bsatrom** [comment]
DO YOUR WORST!

**Comment by tjvantoll** [comment]
Denied!

![screen shot 2014-04-15 at 1 06 08 pm](https://cloud.githubusercontent.com/assets/544280/2710352/49c6ccd6-c4c0-11e3-9845-48ccadd24c52.png)

**Comment by bsatrom** [comment]
good to know! Ok, new issues in the stock responses, then.
